GRADE_STATS = {
    "C":  {"hp": 3000, "attack": 280, "defense": 120},
    "B":  {"hp": 4000, "attack": 350, "defense": 160},
    "A":  {"hp": 5200, "attack": 440, "defense": 210},
    "S":  {"hp": 6500, "attack": 550, "defense": 270},
    "SS": {"hp": 8000, "attack": 680, "defense": 340},
}

STAR_BONUS = {1: 0, 2: 0.08, 3: 0.16, 4: 0.25, 5: 0.35}

GRADE_ORDER = ["C", "B", "A", "S", "SS"]

GACHA_RATES = {
    "C":  0.40,
    "B":  0.30,
    "A":  0.18,
    "S":  0.09,
    "SS": 0.03,
}

CHARACTERS = {
    "gusion": {
        "name": "Gusion",
        "origin": "Mobile Legends",
        "base_grade": "C",
        "role": "Assassin",
        "image": "gusion.jpg",
        "is_starter": True,
        "skills": [
            {
                "id": "sword_spike",
                "name": "Sword Spike",
                "description": "Lempar 3 belati ke 1 target. Jika ketiga kena, damage terakhir double.",
                "type": "damage",
                "target": "single_enemy",
                "hits": 3,
                "damage_multiplier": 0.4,
                "last_hit_double": True,
                "effect": None,
            },
            {
                "id": "shadowblade_slaughter",
                "name": "Shadowblade Slaughter",
                "description": "Teleport ke belakang musuh, damage besar + ignore 30% defense target.",
                "type": "damage",
                "target": "single_enemy",
                "damage_multiplier": 1.4,
                "ignore_defense": 0.30,
                "effect": None,
            },
            {
                "id": "incandescence",
                "name": "Incandescence",
                "description": "Nyalakan semua belati. Buff attack sendiri + skill berikutnya +50% damage.",
                "type": "buff",
                "target": "self",
                "damage_multiplier": 0,
                "effect": {"type": "attack_up", "value": 0.25, "duration": 2},
                "next_skill_boost": 0.50,
            },
            {
                "id": "purification",
                "name": "Purification",
                "description": "Teleport kilat ke semua musuh, damage ke semua target + reset kartu di tangan.",
                "type": "damage",
                "target": "all_enemy",
                "damage_multiplier": 0.8,
                "reset_cards": True,
                "effect": None,
            },
        ],
    },

    "tanjiro": {
        "name": "Tanjiro",
        "origin": "Kimetsu no Yaiba",
        "base_grade": "C",
        "role": "Balanced Fighter",
        "image": "tanjiro.jpg",
        "is_starter": True,
        "skills": [
            {
                "id": "water_surface_slash",
                "name": "Water Surface Slash",
                "description": "Damage ke 1 target + heal diri sendiri sedikit.",
                "type": "damage",
                "target": "single_enemy",
                "damage_multiplier": 1.0,
                "self_heal": 0.15,
                "effect": None,
            },
            {
                "id": "flowing_dance",
                "name": "Flowing Dance",
                "description": "Damage kecil ke semua musuh.",
                "type": "damage",
                "target": "all_enemy",
                "damage_multiplier": 0.55,
                "effect": None,
            },
            {
                "id": "striking_tide",
                "name": "Striking Tide",
                "description": "Damage besar ke 1 target + stun 1 giliran.",
                "type": "damage",
                "target": "single_enemy",
                "damage_multiplier": 1.3,
                "effect": {"type": "stun", "duration": 1},
            },
            {
                "id": "hinokami_kagura",
                "name": "Hinokami Kagura",
                "description": "Damage sangat besar ke 1 target + burn beberapa giliran.",
                "type": "damage",
                "target": "single_enemy",
                "damage_multiplier": 1.6,
                "effect": {"type": "burn", "value": 0.08, "duration": 3},
            },
        ],
    },

    "sakura": {
        "name": "Sakura",
        "origin": "Naruto",
        "base_grade": "C",
        "role": "Support/Healer",
        "image": "sakura.jpg",
        "is_starter": True,
        "skills": [
            {
                "id": "cherry_blossom_punch",
                "name": "Cherry Blossom Punch",
                "description": "Damage besar ke 1 target + chance stun 40%.",
                "type": "damage",
                "target": "single_enemy",
                "damage_multiplier": 1.2,
                "effect": {"type": "stun", "duration": 1, "chance": 0.40},
            },
            {
                "id": "mystical_palm",
                "name": "Mystical Palm",
                "description": "Heal 1 ally dengan HP paling rendah.",
                "type": "heal",
                "target": "lowest_hp_ally",
                "heal_multiplier": 1.2,
                "effect": None,
            },
            {
                "id": "byakugou_seal",
                "name": "Byakugou Seal",
                "description": "Heal semua ally + remove 1 status efek negatif dari semua ally.",
                "type": "heal",
                "target": "all_ally",
                "heal_multiplier": 0.6,
                "cleanse": True,
                "effect": None,
            },
            {
                "id": "strength_of_hundred",
                "name": "Strength of a Hundred",
                "description": "Buff defense semua ally + heal diri sendiri.",
                "type": "buff",
                "target": "all_ally",
                "damage_multiplier": 0,
                "self_heal": 0.20,
                "effect": {"type": "defense_up", "value": 0.30, "duration": 2},
            },
        ],
    },

    "levi": {
        "name": "Levi Ackerman",
        "origin": "Attack on Titan",
        "base_grade": "B",
        "role": "Agile Counter",
        "image": "levi.jpg",
        "is_starter": False,
        "skills": [
            {
                "id": "omnidirectional_slash",
                "name": "Omnidirectional Slash",
                "description": "Serang 1 target 4 kali, damage kecil per hit.",
                "type": "damage",
                "target": "single_enemy",
                "hits": 4,
                "damage_multiplier": 0.35,
                "effect": None,
            },
            {
                "id": "thunder_spear",
                "name": "Thunder Spear",
                "description": "Damage besar ke 1 target + ignore 50% defense.",
                "type": "damage",
                "target": "single_enemy",
                "damage_multiplier": 1.5,
                "ignore_defense": 0.50,
                "effect": None,
            },
            {
                "id": "counter_stance",
                "name": "Counter Stance",
                "description": "Buff diri sendiri. Jika diserang giliran ini, balik 30% damage ke penyerang.",
                "type": "buff",
                "target": "self",
                "damage_multiplier": 0,
                "effect": {"type": "counter", "value": 0.30, "duration": 1},
            },
            {
                "id": "ackerman_awakening",
                "name": "Ackerman Awakening",
                "description": "Damage sangat besar ke 1 target + lifesteal 40% damage jadi HP Levi.",
                "type": "damage",
                "target": "single_enemy",
                "damage_multiplier": 1.7,
                "lifesteal": 0.40,
                "effect": None,
            },
        ],
    },

    "giyu": {
        "name": "Giyu Tomioka",
        "origin": "Kimetsu no Yaiba",
        "base_grade": "B",
        "role": "Defensive Counter",
        "image": "giyu.jpg",
        "is_starter": False,
        "skills": [
            {
                "id": "dead_calm",
                "name": "Dead Calm",
                "description": "Block semua serangan giliran ini + balik 20% damage ke semua penyerang.",
                "type": "buff",
                "target": "self",
                "damage_multiplier": 0,
                "effect": {"type": "block_all", "reflect": 0.20, "duration": 1},
            },
            {
                "id": "eighth_form",
                "name": "Water Breathing: Eighth Form",
                "description": "Damage besar ke 1 target + remove semua buff dari target.",
                "type": "damage",
                "target": "single_enemy",
                "damage_multiplier": 1.4,
                "dispel": True,
                "effect": None,
            },
            {
                "id": "piercing_raindrop",
                "name": "Piercing Rain Drop",
                "description": "Damage ke 1 target + defense down target selama 2 giliran.",
                "type": "damage",
                "target": "single_enemy",
                "damage_multiplier": 1.1,
                "effect": {"type": "defense_down", "value": 0.25, "duration": 2},
            },
            {
                "id": "eleventh_form",
                "name": "Eleventh Form: Lull",
                "description": "Cleanse semua ally dari status efek negatif + heal semua ally sedikit.",
                "type": "heal",
                "target": "all_ally",
                "heal_multiplier": 0.4,
                "cleanse": True,
                "effect": None,
            },
        ],
    },

    "angela": {
        "name": "Angela",
        "origin": "Mobile Legends",
        "base_grade": "A",
        "role": "Premium Healer",
        "image": "angela.jpg",
        "is_starter": False,
        "skills": [
            {
                "id": "puppet_string",
                "name": "Puppet On A String",
                "description": "Damage kecil ke 1 target + slow (kurangi giliran efektif target).",
                "type": "damage",
                "target": "single_enemy",
                "damage_multiplier": 0.7,
                "effect": {"type": "slow", "duration": 1},
            },
            {
                "id": "healing_spell",
                "name": "Healing Spell",
                "description": "Heal ally HP paling rendah + beri shield yang menyerap damage 2 giliran.",
                "type": "heal",
                "target": "lowest_hp_ally",
                "heal_multiplier": 1.0,
                "effect": {"type": "shield", "value": 0.20, "duration": 2},
            },
            {
                "id": "love_waves",
                "name": "Love Waves",
                "description": "Heal semua ally bertahap selama 2 giliran + buff defense semua ally.",
                "type": "heal",
                "target": "all_ally",
                "heal_multiplier": 0.4,
                "heal_over_turns": 2,
                "effect": {"type": "defense_up", "value": 0.20, "duration": 2},
            },
            {
                "id": "heartguard",
                "name": "Heartguard",
                "description": "1 ally kebal dari kematian selama 1 giliran (HP tidak bisa turun di bawah 1).",
                "type": "buff",
                "target": "single_ally",
                "damage_multiplier": 0,
                "effect": {"type": "undying", "duration": 1},
            },
        ],
    },

    "muzan": {
        "name": "Kibutsuji Muzan",
        "origin": "Kimetsu no Yaiba",
        "base_grade": "S",
        "role": "Dark Mage",
        "image": "muzan.jpg",
        "is_starter": False,
        "skills": [
            {
                "id": "blood_whip",
                "name": "Blood Whip",
                "description": "Damage besar ke 1 target + bleed 2 giliran.",
                "type": "damage",
                "target": "single_enemy",
                "damage_multiplier": 1.3,
                "effect": {"type": "bleed", "value": 0.07, "duration": 2},
            },
            {
                "id": "cellular_regeneration",
                "name": "Cellular Regeneration",
                "description": "Heal diri sendiri sangat besar + remove 1 status efek negatif.",
                "type": "heal",
                "target": "self",
                "heal_multiplier": 1.5,
                "cleanse": True,
                "effect": None,
            },
            {
                "id": "curse_mark",
                "name": "Curse Mark",
                "description": "Tandai 1 musuh. Musuh tersebut tidak bisa di-heal selama 2 giliran.",
                "type": "debuff",
                "target": "single_enemy",
                "damage_multiplier": 0,
                "effect": {"type": "heal_block", "duration": 2},
            },
            {
                "id": "demon_transformation",
                "name": "Demon Transformation",
                "description": "Buff semua stat diri sendiri + turunin attack semua musuh 1 giliran.",
                "type": "buff",
                "target": "self",
                "damage_multiplier": 0,
                "effect": {"type": "all_stats_up", "value": 0.30, "duration": 2},
                "aoe_debuff": {"type": "attack_down", "value": 0.25, "duration": 1},
            },
        ],
    },

    "cyclops": {
        "name": "Cyclops",
        "origin": "Mobile Legends",
        "base_grade": "S",
        "role": "Mage Support",
        "image": "cyclops.jpg",
        "is_starter": False,
        "skills": [
            {
                "id": "starfall",
                "name": "Starfall",
                "description": "Damage ke semua musuh + chance stun 30% masing-masing.",
                "type": "damage",
                "target": "all_enemy",
                "damage_multiplier": 0.7,
                "effect": {"type": "stun", "duration": 1, "chance": 0.30},
            },
            {
                "id": "planet_attack",
                "name": "Planet Attack",
                "description": "Damage besar ke 1 target + defense down target 2 giliran.",
                "type": "damage",
                "target": "single_enemy",
                "damage_multiplier": 1.4,
                "effect": {"type": "defense_down", "value": 0.30, "duration": 2},
            },
            {
                "id": "big_bang",
                "name": "Big Bang",
                "description": "Damage ke semua musuh + buff attack semua ally.",
                "type": "damage",
                "target": "all_enemy",
                "damage_multiplier": 0.8,
                "ally_buff": {"type": "attack_up", "value": 0.20, "duration": 2},
                "effect": None,
            },
            {
                "id": "astral_force",
                "name": "Astral Force",
                "description": "Refresh kartu di tangan + buff semua stat ally 1 giliran.",
                "type": "buff",
                "target": "all_ally",
                "damage_multiplier": 0,
                "reset_cards": True,
                "effect": {"type": "all_stats_up", "value": 0.25, "duration": 1},
            },
        ],
    },

    "naruto_bm": {
        "name": "Naruto (Baryon Mode)",
        "origin": "Naruto",
        "base_grade": "SS",
        "role": "Drain Fighter",
        "image": "naruto_bm.jpg",
        "is_starter": False,
        "skills": [
            {
                "id": "baryon_fist",
                "name": "Baryon Fist",
                "description": "Damage besar ke 1 target + drain HP musuh, transfer sebagian ke Naruto.",
                "type": "damage",
                "target": "single_enemy",
                "damage_multiplier": 1.4,
                "drain": 0.30,
                "effect": None,
            },
            {
                "id": "cellular_decay",
                "name": "Cellular Decay",
                "description": "Kurangi Attack + Defense 1 musuh secara permanen (tidak bisa di-cleanse).",
                "type": "debuff",
                "target": "single_enemy",
                "damage_multiplier": 0,
                "effect": {"type": "permanent_stat_down", "attack_down": 0.20, "defense_down": 0.20},
            },
            {
                "id": "life_force_burst",
                "name": "Life Force Burst",
                "description": "Damage ke semua musuh + tiap musuh yang kena kehilangan 1 giliran.",
                "type": "damage",
                "target": "all_enemy",
                "damage_multiplier": 0.9,
                "effect": {"type": "skip_turn", "duration": 1},
            },
            {
                "id": "ashura_kurama",
                "name": "Ashura Kurama",
                "description": "Damage masif ke 1 target. Jika target mati, sisa damage limpah ke musuh berikutnya.",
                "type": "damage",
                "target": "single_enemy",
                "damage_multiplier": 2.2,
                "overflow_damage": True,
                "effect": None,
            },
        ],
    },

    "luffy_g5": {
        "name": "Luffy (Gear 5)",
        "origin": "One Piece",
        "base_grade": "SS",
        "role": "Chaos Fighter",
        "image": "luffy_g5.jpg",
        "is_starter": False,
        "skills": [
            {
                "id": "gum_gum_gigant",
                "name": "Gum Gum Gigant",
                "description": "Damage sangat besar ke 1 target + knockback (skip giliran target berikutnya).",
                "type": "damage",
                "target": "single_enemy",
                "damage_multiplier": 1.8,
                "effect": {"type": "skip_turn", "duration": 1},
            },
            {
                "id": "drums_of_liberation",
                "name": "Drums of Liberation",
                "description": "Heal semua ally besar + randomize ulang semua kartu di tangan.",
                "type": "heal",
                "target": "all_ally",
                "heal_multiplier": 0.8,
                "reset_cards": True,
                "effect": None,
            },
            {
                "id": "bajrang_gun",
                "name": "Bajrang Gun",
                "description": "Damage masif ke semua musuh + chance stun 50% semua target.",
                "type": "damage",
                "target": "all_enemy",
                "damage_multiplier": 1.2,
                "effect": {"type": "stun", "duration": 1, "chance": 0.50},
            },
            {
                "id": "toon_force",
                "name": "Toon Force",
                "description": "Kebal dari 1 serangan apapun giliran ini + balik 50% damage ke penyerang.",
                "type": "buff",
                "target": "self",
                "damage_multiplier": 0,
                "effect": {"type": "invincible_counter", "reflect": 0.50, "duration": 1},
            },
        ],
    },
}